"""add column employee_id to review table

Revision ID: a92393123443
Revises: 86cfe95e9496
Create Date: 2024-10-04 15:08:29.574349

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a92393123443'
down_revision = '86cfe95e9496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to add the column and the foreign key contraint
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer,
                                      nullable=True))
        batch_op.create_foreign_key(
            'fk_reviews_employee_id_employees',  # Foreign key name
            'employees',  # Referenced table
            ['employee_id'],  # Column in 'reviews' table
            ['id'])  # Column in 'employees' table
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.drop_constraint('fk_reviews_employee_id_employees',
                                 type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
